version: "3"

services:
  web:
    build: .
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    command: "python store/manage.py runserver 0:8000"
    volumes:
      - .:/home/app
    container_name: django_app

  react-app:
    build:
      context: ./clientapp/onlinestore
      dockerfile: Dockerfile
    volumes:
      - ./clientapp/onlinestore:/home/app
    ports:
      - 8080:3000
    container_name: react_app
    stdin_open: true
    command: "npm start"