# Generated by Django 3.1.4 on 2020-12-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='User',
            new_name='user',
        ),
    ]
